#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/../.."

if [ "${DUNE_CORIOLIS_SAFE_DATA_CLEANUP:-1}" = "0" ]; then
  echo "Coriolis data cleanup is disabled."
  exit 0
fi

effective_wipe_enabled() {
  local map_name="$1" value
  value="$({
    python3 runtime/scripts/usersettings.py map-values "$map_name" 2>/dev/null || true
  } | awk -F '\t' '$1 == "coriolis_db_wipe_enabled" { print tolower($2); exit }')"
  case "$value" in
    false|0|no|off) return 1 ;;
    *) return 0 ;;
  esac
}

cleanup_deepdesert=0
cleanup_hagga=0
effective_wipe_enabled DeepDesert_1 || cleanup_deepdesert=1
effective_wipe_enabled Survival_1 || cleanup_hagga=1

if [ "$cleanup_deepdesert" = "0" ] && [ "$cleanup_hagga" = "0" ]; then
  echo "Coriolis database wipe is enabled; the game will clean cycle data."
  exit 0
fi

if ! docker ps --format '{{.Names}}' | grep -qx dune-postgres; then
  echo "PostgreSQL is not running; Coriolis cycle data cleanup was skipped." >&2
  exit 1
fi

# The game's marker cleanup accepts a keep-list rather than a delete-list. Build
# that keep-list from the live table while it is locked, preserving every
# unknown marker type and deleting only categories known to be regenerated by
# a Coriolis. This deliberately never calls the actor/partition cleanup path.
docker exec -i \
  dune-postgres psql -X -v ON_ERROR_STOP=1 \
  -v cleanup_deepdesert="$cleanup_deepdesert" \
  -v cleanup_hagga="$cleanup_hagga" \
  -U dune -d dune <<'SQL'
BEGIN;
SET LOCAL search_path TO dune, public;
LOCK TABLE dune.markers IN SHARE ROW EXCLUSIVE MODE;

CREATE TEMP TABLE coriolis_cleanup_scope (
  map_name text PRIMARY KEY
) ON COMMIT DROP;

INSERT INTO coriolis_cleanup_scope (map_name)
SELECT 'DeepDesert' WHERE :'cleanup_deepdesert' = '1'
UNION ALL
SELECT 'HaggaBasin' WHERE :'cleanup_hagga' = '1';

CREATE TEMP TABLE coriolis_marker_cleanup_targets (
  map_name text NOT NULL,
  marker_type text NOT NULL,
  PRIMARY KEY (map_name, marker_type)
) ON COMMIT DROP;

INSERT INTO coriolis_marker_cleanup_targets (map_name, marker_type)
SELECT DISTINCT mn.map_name, (m.marker).marker_type
FROM dune.markers m
JOIN dune.map_names mn USING (map_name_id)
WHERE
  (
    EXISTS (SELECT 1 FROM coriolis_cleanup_scope WHERE map_name = 'DeepDesert')
    AND mn.map_name = 'DeepDesert'
    AND (
      (m.marker).marker_type ~ '(Ore|Pickup|Rock|Part|Wreckage|Bush|Field|Seed)$'
      OR (m.marker).marker_type IN ('Cave', 'Shipwreck', 'EnemyCamp', 'EnemyOutpost', 'EnemyLaborOutpost')
      OR (m.marker).marker_type LIKE 'Hazard\_%' ESCAPE '\'
    )
  )
  OR
  (
    EXISTS (SELECT 1 FROM coriolis_cleanup_scope WHERE map_name = 'HaggaBasin')
    AND mn.map_name = 'HaggaBasin'
    AND (m.marker).marker_type ~ '(Ore|Pickup|Rock|Part|Wreckage|Bush|Field|Seed)$'
  );

DO $cleanup$
DECLARE
  current_map text;
  keep_types text[];
  removed_count bigint;
BEGIN
  FOREACH current_map IN ARRAY ARRAY['DeepDesert', 'HaggaBasin'] LOOP
    IF NOT EXISTS (SELECT 1 FROM coriolis_cleanup_scope scope WHERE scope.map_name = current_map) THEN
      CONTINUE;
    END IF;

    SELECT count(*) INTO removed_count
    FROM dune.markers m
    JOIN dune.map_names mn USING (map_name_id)
    JOIN coriolis_marker_cleanup_targets t
      ON t.map_name = mn.map_name AND t.marker_type = (m.marker).marker_type
    WHERE mn.map_name = current_map;

    SELECT coalesce(array_agg(DISTINCT (m.marker).marker_type), ARRAY[]::text[])
      INTO keep_types
    FROM dune.markers m
    JOIN dune.map_names mn USING (map_name_id)
    LEFT JOIN coriolis_marker_cleanup_targets t
      ON t.map_name = mn.map_name AND t.marker_type = (m.marker).marker_type
    WHERE mn.map_name = current_map AND t.marker_type IS NULL;

    PERFORM dune.delete_markers_for_all_players(keep_types, current_map);
    RAISE NOTICE 'Coriolis marker cleanup: map=%, removed=%', current_map, removed_count;
  END LOOP;
END
$cleanup$;

DO $cleanup$
DECLARE
  removed_count bigint := 0;
BEGIN
  IF EXISTS (SELECT 1 FROM coriolis_cleanup_scope WHERE map_name = 'DeepDesert')
     AND to_regclass('dune.resourcefield_state') IS NOT NULL THEN
    DELETE FROM dune.resourcefield_state WHERE map = 'DeepDesert';
    GET DIAGNOSTICS removed_count = ROW_COUNT;
    RAISE NOTICE 'Coriolis resource-field cleanup: map=DeepDesert, removed=%', removed_count;
  END IF;
END
$cleanup$;

COMMIT;
SQL

echo "Coriolis cycle data cleanup completed without touching actors or structures."
